# Customer Experience Analytics Configuration

# Scraping Configuration
scraping:
  reviews_per_bank: 400
  max_retries: 3
  delay: 1
  timeout: 30

# Database Configuration
database:
  host: localhost
  port: 1521
  service: XE
  user: hr
  password: password

# NLP Configuration
nlp:
  sentiment_model: distilbert-base-uncased-finetuned-sst-2-english
  spacy_model: en_core_web_sm
  max_features: 100

# Visualization Configuration
visualization:
  figure_size: [12, 8]
  dpi: 300
  style: seaborn-v0_8

# Analysis Configuration
analysis:
  min_reviews_per_bank: 300
  sentiment_threshold: 0.5
  theme_min_frequency: 5
